name: test action
on:
  push


jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: A job to test
    steps:
      - name: create a file
        run: echo 'hello test' > test.txt

      - name: chckout code
        uses: actions/checkout@v2

      - name: test action
        id: hello
        uses: ./actions-a
        with:
          input_file: ./test.txt
          out_path: ./test2.txt

      - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: Example txt
            path: ./test2.txt