name: test action
on:
  push

jobs:
  my_first_job:
    runs-on: ubuntu:latest
    name: A job to test
    steps:
      - name: test action
        id: hello
        uses: ./actions-a
        with:
          - first_value: 'first test'