name: test action
on:
  push

env:
  IN_PATH: in
  OUT_PATH: out

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: A job to test
    steps:
      - name: create a file
        run: mkdir -p ${{env.IN_PATH}} && echo 'some test to write' > ${{env.IN_PATH}}/text.txt
      - name: chckout code
        uses: actions/checkout@v2
      - name: test action
        id: hello
        uses: ./actions-a
        with:
          in_path: ${{env.IN_PATH}}
          out_path: ${{env.OUT_PATH}}